name: Add issues and PRs to Sia project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    uses: The-Bigfile/workflows/.github/workflows/project-add.yml@dev
    secrets: inherit
